name: FlujoMX
description: "FlujoMX es una app móvil en Flutter para monitorear el flujo de agua en tiempo real y generar facturas de uso, con alertas configurables y reportes históricos de consumo."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  fl_chart: ^0.69.0
  flutter_background_service: ^5.0.10
  flutter_local_notifications: ^17.2.4
  mqtt_client: ^10.5.1
  sqflite: ^2.4.0
  path: ^1.9.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
